export const sampleCreators = [
  {
    username: 'ocean_guardian',
    display_name: 'Ocean Guardian Project',
    bio: 'Protecting marine life and cleaning our oceans through community-led initiatives. We organize beach cleanups and work with local communities to reduce plastic waste.',
    avatar_url: 'https://images.pexels.com/photos/3278215/pexels-photo-3278215.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/1001682/pexels-photo-1001682.jpeg?auto=compress&cs=tinysrgb&w=1200',
    category: 'Environment',
    subcategory: 'Ocean Cleanup',
    location: 'California, USA',
    organization_type: 'nonprofit',
    is_creator: true,
    monthly_supporters: 342,
    current_amount: 12500,
    goal_amount: 25000
  },
  {
    username: 'wildlife_rescue',
    display_name: 'Wildlife Rescue Alliance',
    bio: 'Saving injured wildlife and rehabilitating animals back to their natural habitats. Operating 24/7 rescue hotline for distressed animals.',
    avatar_url: 'https://images.pexels.com/photos/3551227/pexels-photo-3551227.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/2361952/pexels-photo-2361952.jpeg?auto=compress&cs=tinysrgb&w=1200',
    category: 'Animals',
    subcategory: 'Wildlife Conservation',
    location: 'Colorado, USA',
    organization_type: 'nonprofit',
    is_creator: true,
    monthly_supporters: 518,
    current_amount: 28000,
    goal_amount: 40000
  },
  {
    username: 'community_kitchen',
    display_name: 'Community Kitchen Initiative',
    bio: 'Providing hot meals to families in need and running a food bank for our local community. Every donation helps feed someone hungry.',
    avatar_url: 'https://images.pexels.com/photos/6646917/pexels-photo-6646917.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=1200',
    category: 'People',
    subcategory: 'Community',
    location: 'New York, USA',
    organization_type: 'nonprofit',
    is_creator: true,
    monthly_supporters: 627,
    current_amount: 45000,
    goal_amount: 60000
  },
  {
    username: 'tree_planter',
    display_name: 'Reforestation Warriors',
    bio: 'Planting trees across deforested areas and educating communities about the importance of forests. One tree at a time, we are rebuilding our planet.',
    avatar_url: 'https://images.pexels.com/photos/4503270/pexels-photo-4503270.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg?auto=compress&cs=tinysrgb&w=1200',
    category: 'Environment',
    subcategory: 'Reforestation',
    location: 'Oregon, USA',
    organization_type: 'nonprofit',
    is_creator: true,
    monthly_supporters: 289,
    current_amount: 15000,
    goal_amount: 30000
  },
  {
    username: 'animal_sanctuary',
    display_name: 'Happy Hooves Sanctuary',
    bio: 'A safe haven for rescued farm animals. We provide lifetime care for animals saved from abuse and neglect, giving them the peaceful life they deserve.',
    avatar_url: 'https://images.pexels.com/photos/1471579/pexels-photo-1471579.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/105808/pexels-photo-105808.jpeg?auto=compress&cs=tinysrgb&w=1200',
    category: 'Animals',
    subcategory: 'Animal Rescue',
    location: 'Vermont, USA',
    organization_type: 'nonprofit',
    is_creator: true,
    monthly_supporters: 412,
    current_amount: 22000,
    goal_amount: 35000
  },
  {
    username: 'mental_health_advocate',
    display_name: 'Minds Matter Foundation',
    bio: 'Breaking the stigma around mental health through free counseling sessions and support groups. Everyone deserves access to mental health care.',
    avatar_url: 'https://images.pexels.com/photos/3759058/pexels-photo-3759058.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/3952048/pexels-photo-3952048.jpeg?auto=compress&cs=tinysrgb&w=1200',
    category: 'People',
    subcategory: 'Health',
    location: 'Texas, USA',
    organization_type: 'nonprofit',
    is_creator: true,
    monthly_supporters: 734,
    current_amount: 38000,
    goal_amount: 50000
  },
  {
    username: 'education_hero',
    display_name: 'Books for Every Child',
    bio: 'Bringing books and educational resources to underserved communities. Literacy is the foundation of a brighter future.',
    avatar_url: 'https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/256395/pexels-photo-256395.jpeg?auto=compress&cs=tinysrgb&w=1200',
    category: 'People',
    subcategory: 'Education',
    location: 'Illinois, USA',
    organization_type: 'nonprofit',
    is_creator: true,
    monthly_supporters: 445,
    current_amount: 19000,
    goal_amount: 35000
  },
  {
    username: 'zero_waste_warrior',
    display_name: 'Zero Waste Community',
    bio: 'Teaching sustainable living practices and helping neighborhoods reduce waste to zero. Together we can eliminate single-use plastics.',
    avatar_url: 'https://images.pexels.com/photos/802221/pexels-photo-802221.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/3735218/pexels-photo-3735218.jpeg?auto=compress&cs=tinysrgb&w=1200',
    category: 'Environment',
    subcategory: 'Climate Action',
    location: 'Washington, USA',
    organization_type: 'organization',
    is_creator: true,
    monthly_supporters: 356,
    current_amount: 18000,
    goal_amount: 25000
  },
  {
    username: 'refugee_support',
    display_name: 'New Beginnings Network',
    bio: 'Supporting refugee families with housing, job training, and integration services. Helping new arrivals build their new lives with dignity.',
    avatar_url: 'https://images.pexels.com/photos/6646922/pexels-photo-6646922.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/3184398/pexels-photo-3184398.jpeg?auto=compress&cs=tinysrgb&w=1200',
    category: 'People',
    subcategory: 'Human Rights',
    location: 'Michigan, USA',
    organization_type: 'nonprofit',
    is_creator: true,
    monthly_supporters: 523,
    current_amount: 31000,
    goal_amount: 45000
  },
  {
    username: 'pet_adoption',
    display_name: 'Forever Homes Animal Rescue',
    bio: 'Finding loving homes for abandoned pets and providing medical care until adoption. Every animal deserves a second chance.',
    avatar_url: 'https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/33053/dog-young-dog-small-dog-maltese.jpg?auto=compress&cs=tinysrgb&w=1200',
    category: 'Animals',
    subcategory: 'Pet Adoption',
    location: 'Florida, USA',
    organization_type: 'nonprofit',
    is_creator: true,
    monthly_supporters: 891,
    current_amount: 42000,
    goal_amount: 55000
  },
  {
    username: 'clean_energy',
    display_name: 'Solar for Communities',
    bio: 'Installing solar panels for low-income families and community centers. Making clean energy accessible to everyone.',
    avatar_url: 'https://images.pexels.com/photos/2800832/pexels-photo-2800832.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/433308/pexels-photo-433308.jpeg?auto=compress&cs=tinysrgb&w=1200',
    category: 'Environment',
    subcategory: 'Renewable Energy',
    location: 'Arizona, USA',
    organization_type: 'organization',
    is_creator: true,
    monthly_supporters: 267,
    current_amount: 14000,
    goal_amount: 30000
  },
  {
    username: 'kindness_project',
    display_name: 'Random Acts of Kindness',
    bio: 'Individual spreading joy through daily acts of kindness in my community. From paying for groceries to helping neighbors, small acts create big change.',
    avatar_url: 'https://images.pexels.com/photos/3184613/pexels-photo-3184613.jpeg?auto=compress&cs=tinysrgb&w=200',
    cover_image_url: 'https://images.pexels.com/photos/1739842/pexels-photo-1739842.jpeg?auto=compress&cs=tinysrgb&w=1200',
    category: 'People',
    subcategory: 'Community',
    location: 'Georgia, USA',
    organization_type: 'individual',
    is_creator: true,
    monthly_supporters: 178,
    current_amount: 5000,
    goal_amount: 10000
  }
];
